name: ML Model Training CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  train-model:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        pip install mlflow pandas scikit-learn seaborn matplotlib
    
    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run . --no-conda
    
    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ml-model-artifacts
        path: |
          MLProject/mlruns/
          MLProject/*.pkl
          MLProject/*.joblib
