name: ML Model Training CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  train-model:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.8
    
    - name: Run MLflow Project
      shell: bash -l {0}
      run: |
        cd MLProject
        mlflow run .
    
    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ml-model-artifacts
        path: |
          MLProject/mlruns/
          MLProject/*.pkl
          MLProject/*.joblib
